-- Enable Row Level Security (RLS) on payment_transaction and all public schema tables
ALTER TABLE IF EXISTS "payment_transaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "orders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "order_status_log" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "riders" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "order_item" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "HeroSlide" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "support_conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "support_message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "CustomerReview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "ProductRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS "health_article" ENABLE ROW LEVEL SECURITY;
