-- CreateEnum
CREATE TYPE "ValidationStatus" AS ENUM ('UNVALIDATED', 'CALLED', 'VALIDATED', 'REJECTED');

-- AlterTable
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "paymentMethod" TEXT NOT NULL DEFAULT 'PAY_ON_DELIVERY';
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "deliveryNotes" TEXT;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "validationStatus" "ValidationStatus" NOT NULL DEFAULT 'UNVALIDATED';
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "validatedAt" TIMESTAMP(3);
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "adminCalledAt" TIMESTAMP(3);
